# Generated by Django 4.2.3 on 2023-07-28 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_profiles_subscriber_id_alter_jobs_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiles",
            name="profile_pic",
        ),
        migrations.AlterField(
            model_name="jobs",
            name="time",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="img_url",
            field=models.CharField(
                default="https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg",
                max_length=500,
            ),
        ),
    ]
